/**
 * Changelog Data
 * Auto-generated by scripts/generate_changelog.py
 * Generated: 2026-01-16T17:43:32.508900
 *
 * DO NOT EDIT MANUALLY - Edit docs/CHANGELOG.md and run the script
 */

// =============================================================================
// Types
// =============================================================================

export type SectionType = 'added' | 'changed' | 'fixed' | 'technical' | 'developer-notes' | 'key-guarantee';

export interface ChangeItem {
  text: string;
  details: string[];
}

export interface ChangeSection {
  type: SectionType;
  items: ChangeItem[];
}

export interface VersionEntry {
  version: string;
  date: string;
  title: string;
  sections: ChangeSection[];
}

// =============================================================================
// Config
// =============================================================================

export const SECTION_CONFIG: Record<SectionType, { label: string; icon: string; color: string }> = {
  added: { label: 'Added', icon: '+', color: '#22c55e' },
  changed: { label: 'Changed', icon: '~', color: '#f59e0b' },
  fixed: { label: 'Fixed', icon: '!', color: '#3b82f6' },
  technical: { label: 'Technical', icon: '#', color: '#8b5cf6' },
  'developer-notes': { label: 'Developer Notes', icon: '>', color: '#64748b' },
  'key-guarantee': { label: 'Key Guarantee', icon: '*', color: '#06b6d4' },
};

export const GENERATED_AT = '2026-01-16T17:43:32.508900';

// =============================================================================
// Data
// =============================================================================

export const CHANGELOG_ENTRIES: VersionEntry[] = [
  {
    version: '7.1.0',
    date: '2026-01-16',
    title: 'Zone Layout Designer (PR #80)',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**Zone Layout Designer**: Novel rule-based level editor at `/level-editor`',
            details: [
              'Generate sample dungeons with specific seeds for any floor (1-8)',
              'View zone configurations with color-coded rooms',
              '**Rule Builder**: Visual interface to create asset placement rules',
              'Position strategies: center, corners, walls, entrances, random, perimeter',
              'Count specs: fixed, range, density-based, all positions',
              'Rotation options: fixed angle, face center, face wall, random',
              'Scale and spacing controls',
              '**Presets**: One-click patterns (corner pillars, center statue, wall torches, etc.)',
              '**Python Export**: Generates `@register_layout` code via modal popup',
              'Resizable panels for workflow customization',
            ],
          },
          {
            text: '**Model Library System**: Extracted 3D models into reusable modules',
            details: [
              '`entranceDoors.ts`, `bossThrone.ts`, `pillar.ts`, `statue.ts`',
              'Central registry with categories and metadata',
              'Shared material presets (wood, stone, metal, iron, gold, fabric)',
            ],
          },
          {
            text: '**Model Generator Skill**: Claude skill for procedural Three.js model creation',
            details: [],
          },
          {
            text: '**Presentation Slides**: AI synthesis theory and Level Editor case study',
            details: [],
          },
        ],
      },
      {
        type: 'fixed',
        items: [
          {
            text: 'DieType export causing Vite module errors (type-only export syntax)',
            details: [],
          },
          {
            text: 'WebGL context loss from multiple renderer instances',
            details: [],
          },
          {
            text: 'Passive event listener warnings on map canvas',
            details: [],
          },
          {
            text: 'CharacterPreview3D not appearing on initial load',
            details: [],
          },
          {
            text: 'CharacterPreview3D not updating when race/class changes',
            details: [],
          },
          {
            text: 'Dice animation stuck in rolling state during stat rolling',
            details: [],
          },
          {
            text: 'Dice 3D appearance during rolling',
            details: [],
          },
        ],
      },
      {
        type: 'technical',
        items: [
          {
            text: '`web/src/pages/LevelEditor/`: 8 new components (~3,500 lines)',
            details: [],
          },
          {
            text: '`web/src/models/`: 6 new model files with registry',
            details: [],
          },
          {
            text: '`web/src/services/editorApi.ts`: Editor API client',
            details: [],
          },
          {
            text: '`server/app/api/editor.py`: Backend editor endpoints',
            details: [],
          },
          {
            text: '`.claude/skills/model-generator/SKILL.md`: Model generation skill',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '6.12.0',
    date: '2026-01-16',
    title: 'D&D System Enhancements (PR #77)',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**DEX-Based Initiative**: d20 + DEX modifier for turn order',
            details: [
              'Emits DICE_ROLL events for HUD visualization',
              'Elite/boss enemies get initiative bonuses',
            ],
          },
          {
            text: '**Level-Based Proficiency Bonus**: 2 + (level-1)//4 (D&D 5e formula)',
            details: [
              'Applied to attack rolls, scales with character level',
            ],
          },
          {
            text: '**Hazard Saving Throws**: DEX/CON saves for environmental hazards',
            details: [
              'Lava: DEX DC 15 (half damage on success)',
              'Ice: DEX DC 10 (prevent slide on success)',
              'Poison Gas: CON DC 12 (prevent poison on success)',
              'Deep Water: CON DC 10 (prevent drowning check on success)',
            ],
          },
          {
            text: '**Status Effect CON Saves**: Resist trap status effects',
            details: [
              'Poison: CON DC 12, Burn: CON DC 10',
              'Freeze: CON DC 12, Stun: CON DC 14',
            ],
          },
          {
            text: '**AbilityCheck Foundation**: Dataclass and function for future skill checks',
            details: [],
          },
        ],
      },
      {
        type: 'technical',
        items: [
          {
            text: '`src/combat/battle_manager.py`: DEX initiative rolls with DICE_ROLL events',
            details: [],
          },
          {
            text: '`src/combat/dnd_combat.py`: `calculate_proficiency_bonus()`, `AbilityCheck`, `make_ability_check()`',
            details: [],
          },
          {
            text: '`src/world/hazards.py`: `HAZARD_SAVES` config and saving throw logic',
            details: [],
          },
          {
            text: '`src/world/traps.py`: `STATUS_EFFECT_DCS` and CON save logic',
            details: [],
          },
          {
            text: '`src/core/engine_environment.py`: DICE_ROLL event emission for hazard saves',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '6.11.0',
    date: '2026-01-16',
    title: 'D&D Integration (PR #76)',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**Enemy D&D Stats**: All 28 enemies have armor_class, attack_bonus, damage_dice, ability scores',
            details: [],
          },
          {
            text: '**Weapon Damage Dice**: Equipped weapon\'s dice used in combat',
            details: [],
          },
          {
            text: '**Finesse Weapons**: Daggers use DEX for attack/damage instead of STR',
            details: [],
          },
          {
            text: '**Trap Saving Throws**: DEX save for half damage on traps',
            details: [],
          },
        ],
      },
      {
        type: 'changed',
        items: [
          {
            text: '`seed_database.py` updated with D&D column mappers',
            details: [],
          },
          {
            text: 'Alembic migration 005 adds D&D columns to enemies table',
            details: [],
          },
        ],
      },
      {
        type: 'technical',
        items: [
          {
            text: '`data/seeds/enemies.json`: armor_class (10-16), attack_bonus (0-7), damage_dice (1d4-2d10)',
            details: [],
          },
          {
            text: '`data/seeds/weapons.json`: 16 weapons with damage dice and stat_used',
            details: [],
          },
          {
            text: '`src/items/item/equipment.py`: Weapon class with damage_dice and stat_used',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '6.10.0',
    date: '2026-01-16',
    title: 'D&D Dice Events (PRs #74-75)',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**Dice Rolling Module**: Core dice functions with LUCK influence',
            details: [
              '`roll_die()`, `roll_dice()`, `roll_notation()`, `roll_d20()`',
              'LUCK modifier gives chance to reroll and take better result',
            ],
          },
          {
            text: '**Ability Scores System**: STR, DEX, CON, LUCK',
            details: [
              'Race base stats and modifiers',
              'Class modifiers',
            ],
          },
          {
            text: '**D&D Combat**: Attack rolls vs AC, damage dice, saving throws',
            details: [
              '`make_attack_roll()`: 1d20 + modifier vs target AC',
              '`make_damage_roll()`: weapon dice + modifier',
              '`make_saving_throw()`: 1d20 + ability mod vs DC',
              'Critical hits (nat 20) double damage dice',
              'Fumbles (nat 1) auto-miss',
            ],
          },
          {
            text: '**DICE_ROLL Event Type**: Frontend receives dice roll data',
            details: [],
          },
          {
            text: '**Dice3D Component**: CSS 3D animated dice (d4, d6, d8, d10, d12, d20)',
            details: [],
          },
          {
            text: '**DiceRollHUD**: Battle overlay showing attack/damage/save rolls',
            details: [],
          },
          {
            text: '**StatRoller**: Character creation 3d6 rolling UI',
            details: [],
          },
        ],
      },
      {
        type: 'technical',
        items: [
          {
            text: '`src/core/dice.py`: Dice rolling with LUCK influence',
            details: [],
          },
          {
            text: '`src/entities/ability_scores.py`: AbilityScores dataclass',
            details: [],
          },
          {
            text: '`src/combat/dnd_combat.py`: AttackRoll, DamageRoll, SavingThrow dataclasses',
            details: [],
          },
          {
            text: '`web/src/components/Dice3D/`: 3D animated dice',
            details: [],
          },
          {
            text: '`web/src/components/DiceRollHUD/`: Combat dice overlay',
            details: [],
          },
          {
            text: '`web/src/components/StatRoller/`: Character creation roller',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '6.9.5',
    date: '2026-01-16',
    title: 'UI Migration (PR #73)',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**StatsHUD Component**: Player vitals overlay (HP, gold, level, race)',
            details: [],
          },
          {
            text: '**GameMessagesPanel**: Tabbed message log (All/Combat/System/Lore)',
            details: [],
          },
          {
            text: '**Minimap Component**: Dungeon overview in corner',
            details: [],
          },
          {
            text: '**HelpWindow**: Controls reference overlay (? key)',
            details: [],
          },
          {
            text: '**Terminal Toggle**: Hide/show terminal with Tab key',
            details: [],
          },
          {
            text: '**Keyboard Handler**: Works when terminal hidden',
            details: [],
          },
        ],
      },
      {
        type: 'changed',
        items: [
          {
            text: 'Terminal elements moved to 3D overlay',
            details: [],
          },
          {
            text: 'Play page layout restructured for overlay HUD',
            details: [],
          },
        ],
      },
      {
        type: 'technical',
        items: [
          {
            text: '`web/src/components/StatsHUD/`: Player stats overlay',
            details: [],
          },
          {
            text: '`web/src/components/GameMessagesPanel/`: Tabbed messages',
            details: [],
          },
          {
            text: '`web/src/components/Minimap/`: Dungeon overview',
            details: [],
          },
          {
            text: '`web/src/components/HelpWindow/`: Controls reference',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '6.9.2',
    date: '2026-01-15',
    title: 'CharacterWindow & Combat Polish (PRs #70-71)',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**CharacterWindow Component**: Equipment, inventory, journal tabs',
            details: [],
          },
          {
            text: '**Enemy Attack Bump Animation**: Visual feedback for enemy attacks',
            details: [],
          },
          {
            text: '**Battle Event Fixes**: State synchronization improvements',
            details: [],
          },
        ],
      },
      {
        type: 'technical',
        items: [
          {
            text: '`web/src/components/CharacterWindow/`: Multi-tab character interface',
            details: [],
          },
          {
            text: '`web/src/components/BattleRenderer3D/`: Bump animation system',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '6.9.0',
    date: '2026-01-14',
    title: '3D Asset Database Storage (PR #69)',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**3D Asset Models**: SQLAlchemy models for asset_3d and generation_job tables',
            details: [],
          },
          {
            text: '**Asset REST API**: `/api/assets3d/*` for CRUD operations',
            details: [],
          },
          {
            text: '**AssetsContext**: Frontend global asset state',
            details: [],
          },
          {
            text: '**Seed Data**: 26 asset definitions from assetQueue.ts',
            details: [],
          },
        ],
      },
      {
        type: 'changed',
        items: [
          {
            text: 'JobsContext now uses database-backed API with fallback',
            details: [],
          },
          {
            text: 'assetQueue.ts provides API functions with static fallback',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '6.8.0',
    date: '2026-01-14',
    title: '3D Asset Generation Pipeline (PR #68)',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**Docker Container**: TripoSR + PyTorch CPU in isolated environment',
            details: [],
          },
          {
            text: '**Job Queue System**: JSON file-based job storage',
            details: [],
          },
          {
            text: '**Container Worker**: Polls queue, runs inference, exports GLB',
            details: [],
          },
          {
            text: '**JobsPanel Component**: Real-time progress monitoring',
            details: [],
          },
          {
            text: '**JobsContext**: Global React state for job management',
            details: [],
          },
          {
            text: '**Asset Upload Workflow**: Concept art to GLB generation',
            details: [],
          },
        ],
      },
      {
        type: 'technical',
        items: [
          {
            text: '`tools/3d-pipeline/Dockerfile`: TripoSR dependencies',
            details: [],
          },
          {
            text: '`tools/3d-pipeline/container_worker.py`: Job processor',
            details: [],
          },
          {
            text: '`web/src/components/JobsPanel.tsx`: Progress UI',
            details: [],
          },
          {
            text: '`web/src/contexts/JobsContext.tsx`: Job state',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '6.7.0',
    date: '2026-01-13',
    title: 'Data Persistence Migration',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**JSON Seed Files**: Game balance data in version-controlled JSON (`data/seeds/`)',
            details: [
              '`enemies.json` (28 enemies), `bosses.json` (8 bosses)',
              '`races.json` (5 races), `classes.json` (4 classes)',
              '`items.json` (29 items), `themes.json` (8 dungeon themes)',
              '`combat.json` (traps, hazards, status effects)',
              '`floor_pools.json` (47 floor spawn pools)',
            ],
          },
          {
            text: '**SQLAlchemy Models**: Database tables for all game constants',
            details: [
              '`game_enemies`, `game_bosses`, `game_races`, `game_classes`',
              '`game_items`, `game_themes`, `game_traps`, `game_hazards`',
              '`game_status_effects`, `game_floor_pools`',
            ],
          },
          {
            text: '**Redis Caching Layer**: Cache-aside pattern with 24h TTL',
            details: [
              '`cache_warmer.py` service for startup cache population',
              'Cache invalidation on write operations',
            ],
          },
          {
            text: '**REST API Endpoints**: 11 new endpoints under `/api/game-constants/`',
            details: [
              '`/races`, `/classes`, `/enemies`, `/bosses`, `/items`',
              '`/themes`, `/traps`, `/hazards`, `/status-effects`',
              '`/floor-pools/{floor}`, `/cache-status`',
            ],
          },
          {
            text: '**Pydantic Response Schemas**: Full API documentation with typed responses',
            details: [],
          },
          {
            text: '**useGameConstants Hook**: React hook for frontend data fetching with 5min cache',
            details: [],
          },
          {
            text: '**Database Seeder Script**: `scripts/seed_database.py` populates 141 records',
            details: [],
          },
        ],
      },
      {
        type: 'changed',
        items: [
          {
            text: '`CharacterCreation.tsx` fetches races/classes from API instead of static imports',
            details: [],
          },
          {
            text: '`characterData.ts` reduced to ability descriptions only (removed RACES, CLASSES)',
            details: [],
          },
        ],
      },
      {
        type: 'fixed',
        items: [
          {
            text: 'Circular import in combat module (`battle_actions` ↔ `battle_boss_abilities`)',
            details: [
              'Moved boss ability imports to end of `battle_actions.py`',
              'Added `from __future__ import annotations` to `boss_heuristics.py`',
            ],
          },
        ],
      },
      {
        type: 'technical',
        items: [
          {
            text: '`server/app/api/game_constants.py`: FastAPI router with cached endpoints',
            details: [],
          },
          {
            text: '`server/app/models/game_constants.py`: SQLAlchemy models for all constant types',
            details: [],
          },
          {
            text: '`server/app/schemas/game_constants.py`: Pydantic response schemas',
            details: [],
          },
          {
            text: '`server/app/core/cache.py`: Redis cache utility functions',
            details: [],
          },
          {
            text: '`web/src/hooks/useGameConstants.ts`: React hook with in-memory caching',
            details: [],
          },
          {
            text: '`web/src/services/api.ts`: Added `gameConstantsApi` client',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '6.5.1',
    date: '2026-01-12',
    title: 'Roadmap Complete',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**FloorDiorama3D Component**: 3D floor preview visualization',
            details: [],
          },
          {
            text: '**CharacterPreview3D Component**: Character model preview in creation',
            details: [],
          },
          {
            text: '**Daily Challenge Backend**: Models, service, and API for daily runs',
            details: [],
          },
          {
            text: '**Ice Slide Mechanic**: Momentum-based movement on ice tiles',
            details: [],
          },
        ],
      },
      {
        type: 'technical',
        items: [
          {
            text: 'PRs #21-24 merged completing all priority roadmap items',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '6.4.0',
    date: '2026-01-12',
    title: 'Frontend Lore Alignment',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**AtmosphericPage Component**: Reusable wrapper for immersive pages',
            details: [
              'Layered z-index stacking (background, fog, particles, content, CRT, vignette)',
              'Parallax backgrounds (landing, entrance, kingdom, underground)',
              'Particle systems (dust, embers, mist)',
              'CRT scanline overlay with intensity options',
            ],
          },
          {
            text: '**PhosphorHeader Component**: Animated phosphor text reveals',
            details: [
              'Multiple styles (dramatic, emphasis, normal, whisper)',
              'Configurable delays and completion callbacks',
            ],
          },
          {
            text: '**DungeonPortal3D Component**: Three.js animated dungeon entrance',
            details: [
              'Flickering torch lights, swirling fog, Field glow',
            ],
          },
          {
            text: '**About Page**: "Built by AI" technical showcase',
            details: [
              'Credits for Claude Opus 4.5, ChatGPT 5.2, Suno v4.5, DALL-E 3',
              'Project statistics (50k+ lines, 80+ components, etc.)',
              'Quality markers and philosophy sections',
            ],
          },
          {
            text: '**Features Page**: Game features overview',
            details: [],
          },
          {
            text: '**Presentation Page**: 23-slide AI Usage Case Study for Jan 17 share-out',
            details: [
              'Export/print functionality with proper PDF pagination',
              'Headers (title + author) and footers (event + page numbers)',
              'Title page isolation with page breaks',
              'Author: Blixa Markham a.k.a. DataSci4Fun',
              'Key concepts: Iterative Divergence Protocol, Contextual Displacement',
            ],
          },
        ],
      },
      {
        type: 'changed',
        items: [
          {
            text: '**Home Page**: Complete redesign with Skyfall Seed lore',
            details: [
              'Rotating lore quotes, floor descriptions, Field narrative',
            ],
          },
          {
            text: '**Login Page**: "Resume Your Descent" with DungeonPortal3D background',
            details: [],
          },
          {
            text: '**Register Page**: "Begin Your Legend" with kingdom parallax',
            details: [],
          },
          {
            text: '**CharacterCreation Page**: Race/class lore integration from loreSkyfall.ts',
            details: [],
          },
          {
            text: '**Navigation**: Reorganized into Game/Community dropdowns',
            details: [],
          },
        ],
      },
      {
        type: 'technical',
        items: [
          {
            text: '`web/src/components/AtmosphericPage/` - Atmospheric wrapper',
            details: [],
          },
          {
            text: '`web/src/components/PhosphorHeader/` - Text reveal component',
            details: [],
          },
          {
            text: '`web/src/components/DungeonPortal3D/` - Three.js portal',
            details: [],
          },
          {
            text: '`web/src/data/loreSkyfall.ts` - Centralized lore data',
            details: [],
          },
          {
            text: '`web/src/pages/Presentation.tsx` - 950+ line presentation system',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '6.3.1',
    date: '2026-01-12',
    title: 'Battle Polish',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**Smooth Move Transitions**: Animated entity movement in tactical combat',
            details: [
              'CSS-based slide transitions for all entity moves',
              '200ms duration for responsive feel',
            ],
          },
          {
            text: '**Floating Damage Numbers**: Visual damage feedback in combat',
            details: [
              'Numbers rise and fade above damaged entities',
              'Color-coded: red for damage, green for healing',
              'Staggered timing for multiple hits',
            ],
          },
        ],
      },
      {
        type: 'fixed',
        items: [
          {
            text: '**Reinforcement Enemy Symbols**: Correct enemy glyphs now display for spawned reinforcements',
            details: [],
          },
          {
            text: '**Exploration Mode Safety**: Enemy attacks disabled when not in battle mode',
            details: [
              'Prevents errant damage during exploration transitions',
            ],
          },
        ],
      },
      {
        type: 'technical',
        items: [
          {
            text: '`web/src/components/BattleRenderer3D.tsx`: Smooth transitions and damage numbers',
            details: [],
          },
          {
            text: '`web/src/components/BattleHUD.css`: Animation keyframes for damage display',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '6.3.0',
    date: '2026-01-12',
    title: 'Three.js Battle Renderer',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**Three.js Battle Visualization**: Full 3D tactical arena rendering',
            details: [
              'WebGL-powered arena view replacing Canvas 2D',
              'Camera positioned for isometric tactical overview',
              'Entity meshes with health bar overlays',
              'Tile-based floor with hazard coloring (lava, ice, poison, water)',
            ],
          },
          {
            text: '**Battle HUD Overlay**: React-based UI layer on 3D canvas',
            details: [
              'Reinforcement countdown panel',
              'Ability buttons with cooldown indicators',
              'Turn indicator and action feedback',
            ],
          },
          {
            text: '**Arena Lighting**: Dynamic lighting for atmosphere',
            details: [
              'Ambient and directional lights',
              'Hazard tile glow effects',
            ],
          },
        ],
      },
      {
        type: 'changed',
        items: [
          {
            text: 'Battle mode now uses Three.js renderer instead of Canvas 2D',
            details: [],
          },
          {
            text: 'Improved visual clarity for tactical positioning',
            details: [],
          },
        ],
      },
      {
        type: 'technical',
        items: [
          {
            text: '`web/src/components/BattleRenderer3D.tsx`: Three.js scene setup (1,200+ lines)',
            details: [],
          },
          {
            text: '`web/src/components/BattleHUD.tsx`: Battle UI overlay',
            details: [],
          },
          {
            text: '`web/src/components/BattleHUD.css`: HUD styling',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '6.2.0',
    date: '2026-01-11',
    title: 'Tactical Depth',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**AI Scoring System**: Deterministic action selection for all enemies',
            details: [
              '`enumerate_candidate_actions()` lists legal MOVE/ATTACK/WAIT',
              '`score_action()` with numeric scoring weights (kill priority, damage, positioning)',
              '`choose_action()` with stable tie-breaking for reproducibility',
            ],
          },
          {
            text: '**Hazard Intelligence**: Enemies navigate around hazards intelligently',
            details: [
              'BFS/Dijkstra pathfinding with hazard costs (lava 120, poison 55, water 30, ice 18)',
              'Enemies exit hazardous tiles, avoid stepping into danger',
              'Melee AI pressures player toward hazards (cornering bonus)',
              '`player_safe_escape_count()` for tactical positioning',
            ],
          },
          {
            text: '**Boss Heuristics**: Priority-based signature abilities for 7 boss types',
            details: [
              'Regent: Royal Decree (summon guards), Counterfeit Crown (debuff)',
              'Rat King: Summon Swarm, Plague Bite, Burrow (escape when low HP)',
              'Spider Queen: Web Trap, Poison Bite, Summon Spiders',
              'Frost Giant: Freeze Ground, Ice Blast',
              'Arcane Keeper: Teleport (when adjacent), Arcane Bolt',
              'Flame Lord: Lava Pool, Inferno, Fire Breath',
              'Dragon Emperor: Dragon Fear (round 1), Tail Sweep, Fire Breath',
              'Cooldown tracking per ability, fallback to ai_scoring when no rule matches',
            ],
          },
        ],
      },
      {
        type: 'technical',
        items: [
          {
            text: '`src/combat/ai_scoring.py`: Core scoring engine (682 lines)',
            details: [],
          },
          {
            text: '`src/combat/boss_heuristics.py`: Boss decision rules (585 lines)',
            details: [],
          },
          {
            text: '`src/combat/battle_actions.py`: Boss ability definitions added',
            details: [],
          },
          {
            text: '`src/combat/battle_manager.py`: Integration with boss detection and ability execution',
            details: [],
          },
          {
            text: '28 tests covering determinism, hazard avoidance, and boss behaviors',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '6.2.1',
    date: '2026-01-11',
    title: 'Kiting Heuristics',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**Ranged AI Kiting**: Kiting/spacing heuristics for ranged enemies',
            details: [
              'Preferred range band (3-5, sweet spot 4)',
              'Decisive adjacency penalty (-60) unless killshot',
              'Break melee lock bonus (+20) when escaping to dist >= 3',
              'Avoids reinforcement entry edges and corners',
              'Retreat lane preservation (self-cornering prevention)',
            ],
          },
        ],
      },
      {
        type: 'technical',
        items: [
          {
            text: '`src/combat/ai_kiting.py`: New kiting module (341 lines)',
            details: [],
          },
          {
            text: 'Applies to `RANGED_KITE` and `ELEMENTAL` AI behaviors',
            details: [],
          },
          {
            text: '13 new tests for kiting determinism and behavior',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '6.1.0',
    date: '2026-01-12',
    title: 'Cinematic Glue',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**Transition Orchestrator**: Foundation for no-flicker mode changes',
            details: [
              '`TransitionKind` enum: ENGAGE, WIN, FLEE, DEFEAT, BOSS_VICTORY',
              '`TransitionState` dataclass with timing, skip support, and serialization',
              'Input locking during active transitions',
              'Automatic transition ticking in game loop',
            ],
          },
          {
            text: '**Transition Curtain** (web): Fade-to-black overlay between modes',
            details: [
              'Phase-based animation: fade_in → hold → fade_out',
              'Letterbox bars for cinematic transitions (ENGAGE, BOSS_VICTORY)',
              'Skip support on Space/Escape/Enter when `can_skip=true`',
              'Z-index layered above BattleOverlay, below cutscenes',
            ],
          },
          {
            text: '**Arena Overview Pan**: Camera pan on battle start',
            details: [
              'Overview phases: zoom_out → pan_enemies → pan_player → settle',
              'Hazard tiles (lava, ice, water, poison) highlighted with pulse animation',
              'Reinforcement entry edges highlighted when enemies pending',
              'Skip with Space/Escape, input locked until complete',
              'Duration scales with arena size (9×7: 1.5s, 11×9: 1.8s, 11×11: 2.0s)',
            ],
          },
        ],
      },
      {
        type: 'changed',
        items: [
          {
            text: 'Battle transitions now use curtain instead of instant mode switch',
            details: [],
          },
          {
            text: 'Defeat transition snaps to black immediately (no fade)',
            details: [],
          },
          {
            text: 'BattleOverlay disabled during overview (buttons + keyboard)',
            details: [],
          },
        ],
      },
      {
        type: 'technical',
        items: [
          {
            text: '`TransitionState` in `src/core/events.py` with start/skip/end methods',
            details: [],
          },
          {
            text: '`Engine.start_transition()`, `tick_transition()`, `is_input_locked()` in `src/core/engine.py`',
            details: [],
          },
          {
            text: '`BattleManager` emits transitions on battle start/end',
            details: [],
          },
          {
            text: '`TransitionCurtain.tsx` with requestAnimationFrame-based animation',
            details: [],
          },
          {
            text: 'Camera transform via CSS `scale()` and `translate()` on arena container',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '6.0.0',
    date: '2026-01-11',
    title: 'Tactical Battle Mode',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**Instanced Tactical Combat**: Exploration remains grid-based; combat transitions to 9x7 tactical arenas',
            details: [],
          },
          {
            text: '**Deterministic Battles**: Same seed produces identical arena layouts, reinforcement queues, and spawn positions',
            details: [],
          },
          {
            text: '**Arena Templates**: 6 biome-specific templates with hazard placement (lava lanes, ice patches, etc.)',
            details: [],
          },
          {
            text: '**Class Ability Kits**: 4 classes with 4 abilities each',
            details: [
              'Warrior: Basic Attack, Power Strike (1.5x, 4cd), Shield Wall (2x def, 3cd), Charge (2 tiles + stun, 5cd)',
              'Mage: Basic Attack, Fireball (AOE 3 damage, 4cd), Frost Nova (freeze adjacent, 5cd), Blink (teleport 3, 4cd)',
              'Rogue: Basic Attack, Backstab (2x if behind, 3cd), Smoke Bomb (invisible 2 turns, 5cd), Dash (move 2, 2cd)',
              'Cleric: Basic Attack, Heal (restore 10 HP, 4cd), Smite (holy 1.5x undead, 3cd), Sanctuary (immune 1 turn, 6cd)',
            ],
          },
          {
            text: '**Reinforcement System**: Enemies spawn from arena edges over time',
            details: [
              'Countdown visible in UI',
              'Arrival accelerated by field pulse intensity (0.9x/0.8x/0.7x for minor/moderate/major)',
              'Elite spawns possible on deeper floors',
            ],
          },
          {
            text: '**Battle Artifacts** (v6.0.5):',
            details: [
              'Duplicate Seal: Duplicates consumable effects in battle',
              'Woundglass Shard: Reveals safe tiles and reinforcement ETAs',
              'Oathstone: Vow enforcement continues during battle',
            ],
          },
          {
            text: '**Ghost Battle Effects** (v6.0.5):',
            details: [
              'Champion: +3 temporary HP at battle start',
              'Archivist: Reveals safe tiles at battle start',
              'Beacon: Points player away from reinforcement entry',
            ],
          },
          {
            text: '**Web Battle Overlay**:',
            details: [
              'Real-time arena visualization with tile colors',
              'Entity positions and HP pips',
              'Reinforcement countdown panel',
              'Keyboard controls (WASD move, 1-4 abilities, Space wait, Escape flee)',
              'Artifact status indicators',
            ],
          },
          {
            text: '**Game Integrity Tests** (v6.0.5):',
            details: [
              'Battle payload contract validation (arena_tiles, entities, reinforcements)',
              'Battle determinism snapshot tests (2 seeds verified)',
            ],
          },
        ],
      },
      {
        type: 'changed',
        items: [
          {
            text: 'Combat encounters now transition to instanced arenas instead of bump-to-attack',
            details: [],
          },
          {
            text: 'Victory save handling now preserves ledger/codex to victories.json before clearing autosave',
            details: [],
          },
          {
            text: 'UI mode toggles between EXPLORATION and BATTLE',
            details: [],
          },
        ],
      },
      {
        type: 'technical',
        items: [
          {
            text: '`BattleState`, `BattleEntity`, `PendingReinforcement` types with full serialization',
            details: [],
          },
          {
            text: '`BattleManager` handles turn processing, ability execution, reinforcement spawning',
            details: [],
          },
          {
            text: '`BattleAction` enum for all combat commands',
            details: [],
          },
          {
            text: 'Deterministic seeding for arena generation and reinforcement scheduling',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '5.3.0',
    date: '2026-01-09',
    title: 'Cinematics V2: Death & Victory Cutscenes',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**Death Cutscene**: 5-scene cinematic sequence (Fall, YouDied, AbyssClaims, Fate, Prompt)',
            details: [],
          },
          {
            text: '**Victory Cutscene**: 3-scene cinematic sequence (Seal, World, Legend)',
            details: [],
          },
          {
            text: '**Death Fate Variants**: Random selection (Echo, Hollowed, Silence) locked per death',
            details: [],
          },
          {
            text: '**Victory Legacy Variants**: Random selection (Beacon, Champion, Archivist) locked per victory',
            details: [],
          },
          {
            text: '**Ghost Lore Panels**: Fate/legacy-specific text on summary screens',
            details: [],
          },
          {
            text: '**Death Camera Effect**: 3D renderer slump/roll/pitch animation on death',
            details: [],
          },
          {
            text: '**Death Overlays**: Vignette, blood curtain, eyelids closing CSS effects',
            details: [],
          },
          {
            text: '**Cinematic SFX**: File-based with procedural fallback',
            details: [],
          },
          {
            text: '**Factory Pattern**: createGameOverCutscene() and createVictoryCutscene() for per-game-end randomization',
            details: [],
          },
          {
            text: '**FX Cues**: Flash/pressure effects synced to caption line completion',
            details: [],
          },
        ],
      },
      {
        type: 'changed',
        items: [
          {
            text: 'Begin button restricted to intro cutscene only',
            details: [],
          },
          {
            text: 'Fall scene background transparent for 3D death cam visibility',
            details: [],
          },
          {
            text: 'Unified voice between cutscene and summary panel text',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '5.2.0',
    date: '2026-01-08',
    title: 'Modular Cutscene Engine',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**Modular Cutscene Architecture**: Reusable engine for all cinematics',
            details: [],
          },
          {
            text: '**Retro CRT Text Reveal**: Phosphor ignition effect per character',
            details: [],
          },
          {
            text: '**FX System**: Flash, shake, flicker, pressure effects',
            details: [],
          },
          {
            text: '**FX Cues**: Effects tied to caption line completion',
            details: [],
          },
          {
            text: '**Scene-Scoped CSS**: Per-scene styling via `.cs-scene-{id}` classes',
            details: [],
          },
          {
            text: '**Debug Mode Panel**: Scene iteration tools for development',
            details: [],
          },
          {
            text: '**7-Scene Intro Cutscene**: Full narrative with effects',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '5.1.0',
    date: '2026-01-07',
    title: 'Cinematic Intro & Responsive Renderer',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**Cinematic Intro**: 7 narrative scenes with parallax backgrounds',
            details: [],
          },
          {
            text: '**Particle Effects**: Stars, embers, dust, darkness, magic, ash, mist',
            details: [],
          },
          {
            text: '**Scene Transitions**: Solid black with no bleed-through',
            details: [],
          },
          {
            text: '**Responsive 3D Renderer**: Fills container, adapts to resize',
            details: [],
          },
        ],
      },
      {
        type: 'fixed',
        items: [
          {
            text: 'Scene background transitions now use solid black curtain',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '5.0.0',
    date: '2026-01-07',
    title: '3D Movement Animations & Map Memory',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**Dynamic LOS Render Distance**: View distance based on line-of-sight',
            details: [],
          },
          {
            text: '**Smooth Movement Animations**: 2D and 3D renderers',
            details: [],
          },
          {
            text: '**Smooth Turn Animations**: Camera rotation interpolation',
            details: [],
          },
          {
            text: '**Map Memory**: Explored tiles remain visible (dimmed)',
            details: [],
          },
          {
            text: '**Pure Tile-Based 3D**: Geometry from tile data only',
            details: [],
          },
          {
            text: '**Parallax Skybox**: Depth effect in 3D view',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '4.6.0',
    date: '2026-01-06',
    title: 'Debug Tooling & Rendering Fixes',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**Debug Hotkeys (F8/F9/F10)**: Gameplay debug tools gated behind DEV or `?debug=1`',
            details: [
              'F8: Toggle wireframe overlay (yellow wall boundaries)',
              'F9: Toggle occluded entity silhouettes (red ghosts)',
              'F10: Copy scene snapshot to clipboard (JSON)',
            ],
          },
          {
            text: '**Z-Buffer Occlusion**: Interpolated depth for accurate entity hiding behind walls',
            details: [],
          },
          {
            text: '**useDebugRenderer Hook**: localStorage persistence, environment gating',
            details: [],
          },
          {
            text: '**DebugToast Component**: Visual feedback for debug actions',
            details: [],
          },
          {
            text: '**top_down_window**: Server-side 11x11 grid around player in snapshots',
            details: [],
          },
          {
            text: '**visibleRange**: Corridor info includes visibility bounds for debugging',
            details: [],
          },
        ],
      },
      {
        type: 'fixed',
        items: [
          {
            text: '**corridorInfo Visibility**: Only visible tiles now influence wall geometry',
            details: [
              'Eliminated artifacts from invisible tiles creating fake walls at huge offsets',
              'Left/right walls use visible range bounds instead of full row',
              'Front wall only set if center tile is visible',
            ],
          },
          {
            text: '**Side-wall Z-Buffer**: Interpolated depth values for proper occlusion',
            details: [],
          },
        ],
      },
      {
        type: 'changed',
        items: [
          {
            text: 'Test page scenarios fixed to keep entities within corridor bounds (offset < ±1)',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '4.5.0',
    date: '2026-01-06',
    title: 'Biome Theming & Tile Engine',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**8 Biome Themes**: Dungeon, Ice, Forest, Lava, Crypt, Sewer, Library, Crystal',
            details: [],
          },
          {
            text: '**Tile Loading Engine**: Load custom 64x64 PNG tiles from `/tiles/{biome}/`',
            details: [],
          },
          {
            text: '**Data-Driven Torch System**: Server-side torch placement with raycasting',
            details: [],
          },
          {
            text: '**Wall Decorations**: Procedural moss, cracks, cobwebs',
            details: [],
          },
          {
            text: '**Biome Test Page**: Selector dropdown, brightness slider, tile toggle',
            details: [],
          },
          {
            text: '**Tile Generation Prompts**: AI image generation prompts for each biome',
            details: [],
          },
        ],
      },
      {
        type: 'changed',
        items: [
          {
            text: 'Wall rendering functions accept biome options',
            details: [],
          },
          {
            text: 'Test page has unique scenes per biome (not identical corridors)',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '4.4.1',
    date: '2026-01-05',
    title: 'WebSocket Stability',
    sections: [
      {
        type: 'fixed',
        items: [
          {
            text: 'Duplicate WebSocket connections from React StrictMode',
            details: [],
          },
          {
            text: 'Chat messages not posting',
            details: [],
          },
          {
            text: 'Keyboard shortcuts blocking chat input',
            details: [],
          },
          {
            text: 'Character creation flow (always goes through creation page)',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '4.4.0',
    date: '2026-01-04',
    title: 'Atmosphere & Exploration',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**Compass HUD**: Medieval-style compass strip showing direction',
            details: [],
          },
          {
            text: '**Trap Rendering**: Visual traps with animations (spike, fire, poison, arrow)',
            details: [],
          },
          {
            text: '**Secret Door System**: Hidden doors revealed with Search (F key)',
            details: [],
          },
          {
            text: '**Atmospheric Effects**: Dust particles and fog wisps',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '4.3.0',
    date: '2026-01-03',
    title: 'Visual Overhaul',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**Pure Black Darkness**: True dungeon atmosphere',
            details: [],
          },
          {
            text: '**Aggressive Fog System**: Exponential falloff',
            details: [],
          },
          {
            text: '**FOV Cone Visualization**: Highlighted tiles in view',
            details: [],
          },
          {
            text: '**Visual Test Page**: `/first-person-test` with scenarios',
            details: [],
          },
        ],
      },
      {
        type: 'changed',
        items: [
          {
            text: 'Torches now pierce fog (drawn after overlay)',
            details: [],
          },
          {
            text: 'Darker color palette for walls/floors',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '4.2.2',
    date: '2026-01-02',
    title: 'Turn Commands',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**Q/E Turn Controls**: Rotate facing without moving',
            details: [],
          },
          {
            text: '**X to Quit**: Changed from Q to free it for turning',
            details: [],
          },
        ],
      },
      {
        type: 'fixed',
        items: [
          {
            text: 'First-person view rendering in open rooms',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '4.2.1',
    date: '2026-01-02',
    title: 'Sound Effects',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**24 Procedural Sounds**: Via Web Audio API',
            details: [],
          },
          {
            text: '**Automatic Triggers**: Sounds play on game events',
            details: [],
          },
          {
            text: '**Volume Controls**: Respects master/SFX settings',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '4.2.0',
    date: '2026-01-01',
    title: 'Character Creation',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**5 Races**: Human, Elf, Dwarf, Halfling, Orc',
            details: [],
          },
          {
            text: '**3 Classes**: Warrior, Mage, Rogue',
            details: [],
          },
          {
            text: '**18 Feats**: Combat, Defense, Utility, Special categories',
            details: [],
          },
          {
            text: '**Character HUD**: Race/class/ability display',
            details: [],
          },
          {
            text: '**Demo Account**: `demo` / `DemoPass123`',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '4.1.0',
    date: '2025-12-30',
    title: 'Scene Renderer',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**First-Person 3D View**: Canvas-based dungeon renderer',
            details: [],
          },
          {
            text: '**Directional FOV**: View based on player facing',
            details: [],
          },
          {
            text: '**9 Enemy Visuals**: Unique styles for each enemy type',
            details: [],
          },
          {
            text: '**Entity Animations**: Breathing, bobbing effects',
            details: [],
          },
          {
            text: '**Demo Pages**: `/first-person-demo`, `/scene-demo`',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '4.0.0',
    date: '2025-12-30',
    title: 'Expanded Gameplay',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**6 New Enemies**: Necromancer, Demon, Assassin, Fire/Ice/Lightning Elementals',
            details: [],
          },
          {
            text: '**Status Effects**: Poison, Burn, Freeze, Stun',
            details: [],
          },
          {
            text: '**Traps**: Spike, Fire, Poison, Arrow',
            details: [],
          },
          {
            text: '**Hazards**: Lava, Ice, Poison Gas, Deep Water',
            details: [],
          },
          {
            text: '**New Equipment**: Shields, Rings, Amulets, Ranged, Throwables, Keys',
            details: [],
          },
          {
            text: '**AI Behaviors**: Chase, Ranged Kite, Aggressive, Stealth, Elemental',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '3.5.0',
    date: '2025-12-30',
    title: 'Friends & Social',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**Friends System**: Search, requests, online status',
            details: [],
          },
          {
            text: '**10 New Achievements**: Social Butterfly, Popular, Explorer, etc.',
            details: [],
          },
          {
            text: '**Visual Polish**: Level up flash, damage flash, critical pulse',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '3.4.0',
    date: '2025-12-30',
    title: 'Mobile Support',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**Touch Controls**: D-pad and action buttons',
            details: [],
          },
          {
            text: '**PWA Support**: Installable, service worker caching',
            details: [],
          },
          {
            text: '**Responsive Layout**: Portrait/landscape modes',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '3.3.0',
    date: '2025-12-30',
    title: 'Spectator Mode',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**Live Spectating**: Watch other players\' games',
            details: [],
          },
          {
            text: '**4 Boss Achievements**: Boss Slayer, Kingslayer, etc.',
            details: [],
          },
          {
            text: '**Legendary Items**: Dragon Slayer, Dragon Scale Armor',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '3.2.0',
    date: '2025-12-30',
    title: 'Boss Monsters',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**5 Bosses**: Goblin King, Cave Troll, Lich Lord, Arcane Keeper, Dragon Emperor',
            details: [],
          },
          {
            text: '**10 Boss Abilities**: Summon, AOE, ranged, buffs',
            details: [],
          },
          {
            text: '**Boss Health Bar**: UI panel for boss HP',
            details: [],
          },
          {
            text: '**Guaranteed Loot**: Each boss drops rare items',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '3.1.0',
    date: '2025-12-30',
    title: 'Profiles & Achievements',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**Player Profiles**: Stats, recent games, showcase',
            details: [],
          },
          {
            text: '**20 Achievements**: Combat, Progression, Efficiency, Collection, Special',
            details: [],
          },
          {
            text: '**Achievement Browser**: Filter by category, track progress',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '3.0.0',
    date: '2025-12-30',
    title: 'Multiplayer & Web',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**FastAPI Backend**: REST + WebSocket API',
            details: [],
          },
          {
            text: '**User Accounts**: JWT authentication',
            details: [],
          },
          {
            text: '**Leaderboards**: Global, daily, weekly rankings',
            details: [],
          },
          {
            text: '**Ghost Replays**: Record and watch death runs',
            details: [],
          },
          {
            text: '**Real-time Chat**: Global and whisper messages',
            details: [],
          },
          {
            text: '**React Frontend**: xterm.js game terminal',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '2.2.1',
    date: '2025-12-30',
    title: '',
    sections: [
      {
        type: 'fixed',
        items: [
          {
            text: 'Lore items display content when read',
            details: [],
          },
          {
            text: 'Victory screen shows instead of closing',
            details: [],
          },
          {
            text: 'Save/load for lore items',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '2.2.0',
    date: '2025-12-30',
    title: 'UX & Story',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**Title Screen**: ASCII art menu',
            details: [],
          },
          {
            text: '**Story System**: 12 discoverable lore entries',
            details: [],
          },
          {
            text: '**Auto-Save**: Every 50 turns and on level change',
            details: [],
          },
          {
            text: '**Tutorial Hints**: Contextual tips',
            details: [],
          },
          {
            text: '**Message Log**: Scrollable history (M key)',
            details: [],
          },
          {
            text: '**Death Recap**: Final stats and lore progress',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '2.1.0',
    date: '2025-12-30',
    title: 'Equipment & UI',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**Equipment System**: Weapons and armor with rarity',
            details: [],
          },
          {
            text: '**Full-Screen Inventory**: Equipment display',
            details: [],
          },
          {
            text: '**Character Screen**: Stats view (C key)',
            details: [],
          },
          {
            text: '**Camera System**: Viewport follows player',
            details: [],
          },
        ],
      },
      {
        type: 'changed',
        items: [
          {
            text: 'Major architecture refactor (manager classes)',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '2.0.0',
    date: '2025-12-30',
    title: 'Visual Variety',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: '**6 Enemy Types**: Goblin, Skeleton, Orc, Wraith, Troll, Dragon',
            details: [],
          },
          {
            text: '**Elite Enemies**: 2x stats variants',
            details: [],
          },
          {
            text: '**5 Dungeon Themes**: Stone, Cave, Crypt, Library, Treasury (expanded to 8 in v4.5.0)',
            details: [],
          },
          {
            text: '**Combat Animations**: Hit flash, damage numbers',
            details: [],
          },
          {
            text: '**Item Rarity Colors**: Common → Legendary',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '1.2.0',
    date: '2025-12-30',
    title: '',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: 'Elite enemies with boosted stats',
            details: [],
          },
          {
            text: 'Field of View system',
            details: [],
          },
          {
            text: 'Save/Load with permadeath',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '1.1.0',
    date: '2025-12-30',
    title: '',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: 'XP and leveling system',
            details: [],
          },
        ],
      },
    ],
  },
  {
    version: '1.0.0',
    date: '2025-12-30',
    title: 'Initial Release',
    sections: [
      {
        type: 'added',
        items: [
          {
            text: 'Procedural dungeon generation (BSP)',
            details: [],
          },
          {
            text: 'Bump-to-attack combat',
            details: [],
          },
          {
            text: 'Basic inventory (10 slots)',
            details: [],
          },
          {
            text: 'Health/Strength potions, Teleport scrolls',
            details: [],
          },
          {
            text: '5 dungeon levels',
            details: [],
          },
        ],
      },
    ],
  },
];

// =============================================================================
// Helper Functions
// =============================================================================

export function getLatestVersion(): VersionEntry | undefined {
  return CHANGELOG_ENTRIES[0];
}

export function getVersionByNumber(version: string): VersionEntry | undefined {
  return CHANGELOG_ENTRIES.find(e => e.version === version);
}

export function getMajorVersions(): VersionEntry[] {
  return CHANGELOG_ENTRIES.filter(e => e.version.endsWith('.0.0') || e.version.endsWith('.0'));
}

export function getVersionCount(): number {
  return CHANGELOG_ENTRIES.length;
}

export function getDateRange(): { earliest: string; latest: string } {
  const dates = CHANGELOG_ENTRIES.map(e => e.date).sort();
  return {
    earliest: dates[0] || "",
    latest: dates[dates.length - 1] || "",
  };
}
