export { Home } from './Home';
export { Login } from './Login';
export { Register } from './Register';
export { Play } from './Play';
export { Leaderboard } from './Leaderboard';
export { Ghosts } from './Ghosts';
export { Profile } from './Profile';
export { Achievements } from './Achievements';
export { Spectate } from './Spectate';
