"""
Bestiary creature data - All creature definitions.

This data is built from actual game data in src/core/constants.py.
"""
from .bestiary_models import Ability, LootDrop, Creature


# ============================================================================
# FLOOR THEMES (from src/core/constants.py)
# ============================================================================
FLOOR_THEMES = {
    1: "Stone Dungeon",
    2: "Sewers of Valdris",
    3: "Forest Depths",
    4: "Mirror Valdris",
    5: "Ice Cavern",
    6: "Ancient Library",
    7: "Volcanic Depths",
    8: "Crystal Cave",
}

# AI Behavior descriptions
AI_DESCRIPTIONS = {
    "CHASE": "Pursues player directly using pathfinding",
    "RANGED_KITE": "Maintains distance and uses ranged attacks",
    "AGGRESSIVE": "Rushes player and attacks relentlessly",
    "STEALTH": "Uses invisibility and ambush tactics",
    "ELEMENTAL": "Adapts tactics based on elemental affinity",
}

# Element icons
ELEMENT_ICONS = {
    "FIRE": "🔥",
    "ICE": "❄️",
    "LIGHTNING": "⚡",
    "DARK": "🌑",
}

# Category info
CATEGORIES = {
    "common": {"name": "Common", "description": "Basic enemies found throughout the dungeon", "color": "#6b7280"},
    "elite": {"name": "Elite", "description": "Powerful foes with special abilities", "color": "#3b82f6"},
    "thematic": {"name": "Thematic", "description": "Floor-specific enemies tied to dungeon zones", "color": "#8b5cf6"},
    "rare": {"name": "Rare", "description": "Uncommon variants with unique traits (one per floor)", "color": "#ec4899"},
    "boss": {"name": "Boss", "description": "Floor guardians with devastating power", "color": "#f59e0b"},
}


# ============================================================================
# BESTIARY DATA (from src/core/constants.py ENEMY_STATS and BOSS_STATS)
# ============================================================================

CREATURES: list[Creature] = [
    # === COMMON ENEMIES (Base enemies) ===
    Creature(
        id="goblin",
        name="Goblin",
        category="common",
        description="Weak and common creatures that infest the upper dungeon. Despite their individual frailty, they can be dangerous in numbers.",
        appearance="Small green-skinned humanoid with pointed ears and sharp teeth. Wears crude leather scraps.",
        behavior="Patrols dungeon corridors. Attacks on sight with basic chase AI.",
        floors="1-3",
        health=6,
        damage=1,
        speed="Normal",
        abilities=[
            Ability(name="Claw Swipe", description="Basic melee attack", damage=1),
        ],
        weaknesses=[],
        resistances=[],
        experience=10,
        loot=[
            LootDrop(item="Goblin Tooth", chance="Common"),
            LootDrop(item="Crude Dagger", chance="Rare"),
        ],
        icon="g",
        threat_level=1,
    ),
    Creature(
        id="skeleton",
        name="Skeleton",
        category="common",
        description="Reanimated bones of fallen warriors. They retain some combat instincts and are found throughout most of the dungeon.",
        appearance="Animated human skeleton with glowing eye sockets. May carry rusted weapons.",
        behavior="Standard chase AI. Patrols areas and attacks living creatures.",
        floors="1-6",
        health=8,
        damage=2,
        speed="Normal",
        abilities=[
            Ability(name="Bone Strike", description="Attacks with bony fists or weapon", damage=2),
        ],
        weaknesses=["Blunt weapons"],
        resistances=["Piercing"],
        experience=15,
        loot=[
            LootDrop(item="Bone Fragment", chance="Common"),
            LootDrop(item="Ancient Coin", chance="Rare"),
        ],
        icon="s",
        threat_level=1,
    ),
    Creature(
        id="orc",
        name="Orc",
        category="common",
        description="Brutish warriors that have taken up residence in the mid-level dungeons. Stronger and more resilient than goblins.",
        appearance="Large muscular humanoid with gray-green skin, tusks, and crude armor.",
        behavior="Aggressive pursuit of intruders. Will fight to the death.",
        floors="2-5",
        health=12,
        damage=3,
        speed="Normal",
        abilities=[
            Ability(name="Heavy Blow", description="Powerful melee strike", damage=3),
        ],
        weaknesses=[],
        resistances=[],
        experience=20,
        loot=[
            LootDrop(item="Orc Tusk", chance="Common"),
            LootDrop(item="Crude Axe", chance="Rare"),
        ],
        icon="o",
        threat_level=2,
    ),
    Creature(
        id="wraith",
        name="Wraith",
        category="common",
        description="Incorporeal spirits of those who died with unfinished business. Fast and deadly, they haunt the deeper floors.",
        appearance="Translucent ghostly figure in tattered robes. Face twisted in eternal anguish.",
        behavior="Swift and relentless pursuit. Can phase through some obstacles.",
        floors="3-8",
        health=10,
        damage=4,
        speed="Fast",
        abilities=[
            Ability(name="Spectral Touch", description="Chilling attack that bypasses armor", damage=4),
        ],
        weaknesses=["Holy", "Light"],
        resistances=["Physical"],
        experience=25,
        loot=[
            LootDrop(item="Ectoplasm", chance="Common"),
            LootDrop(item="Spirit Essence", chance="Rare"),
        ],
        icon="W",
        threat_level=2,
    ),
    Creature(
        id="troll",
        name="Troll",
        category="common",
        description="Massive regenerating brutes found in the lower dungeon. Their wounds heal rapidly unless burned.",
        appearance="Towering humanoid with gray warty skin, long arms, and a hunched posture.",
        behavior="Aggressive pursuit. Will not flee even when badly wounded.",
        floors="5-8",
        health=20,
        damage=5,
        speed="Slow",
        abilities=[
            Ability(name="Crushing Blow", description="Devastating melee attack", damage=5),
            Ability(name="Regeneration", description="Slowly recovers health", effect="Passive healing"),
        ],
        weaknesses=["Fire"],
        resistances=[],
        experience=35,
        loot=[
            LootDrop(item="Troll Hide", chance="Common"),
            LootDrop(item="Troll Blood", chance="Rare"),
        ],
        icon="T",
        threat_level=3,
    ),

    # === ELITE ENEMIES (v4.0 advanced enemies) ===
    Creature(
        id="dragon",
        name="Dragon",
        category="elite",
        description="Ancient wyrms that have made their lair in the Crystal Cave. Rarely encountered but devastatingly powerful.",
        appearance="Massive scaled reptile with wings and glowing eyes. Flames lick between its teeth.",
        behavior="Territorial. Uses fire breath at range, claws up close.",
        floors="8 only",
        health=50,
        damage=10,
        speed="Normal",
        abilities=[
            Ability(name="Fire Breath", description="Cone of flames", damage=10, effect="Burn"),
            Ability(name="Claw Rake", description="Devastating claw attack", damage=8),
            Ability(name="Tail Sweep", description="Knockback attack", damage=6, effect="Knockback"),
        ],
        weaknesses=["Ice"],
        resistances=["Fire"],
        experience=100,
        loot=[
            LootDrop(item="Dragon Scale", chance="Common"),
            LootDrop(item="Dragon Fang", chance="Rare"),
            LootDrop(item="Dragon Heart", chance="Very Rare"),
        ],
        icon="D",
        threat_level=5,
    ),
    Creature(
        id="necromancer",
        name="Necromancer",
        category="elite",
        description="Dark mages who draw power from death itself. They command the undead and strike from afar with dark magic.",
        appearance="Robed figure with pale skin and glowing purple eyes. Carries a staff topped with a skull.",
        behavior="Maintains distance using ranged attacks. Summons skeletons when threatened.",
        floors="3-8",
        health=25,
        damage=8,
        speed="Normal",
        abilities=[
            Ability(name="Dark Bolt", description="Ranged dark magic attack", damage=8),
            Ability(name="Raise Skeleton", description="Summons an undead minion", effect="Summon"),
        ],
        weaknesses=["Holy", "Light"],
        resistances=["Dark", "Poison"],
        experience=40,
        loot=[
            LootDrop(item="Dark Tome", chance="Common"),
            LootDrop(item="Necromancer Staff", chance="Rare"),
        ],
        icon="N",
        threat_level=3,
    ),
    Creature(
        id="demon",
        name="Demon",
        category="elite",
        description="Infernal beings drawn to the volcanic depths. They attack with brutal aggression and fire magic.",
        appearance="Red-skinned humanoid with horns, clawed hands, and flames dancing across their body.",
        behavior="Extremely aggressive. Rushes enemies and uses fire attacks relentlessly.",
        floors="4-8",
        health=45,
        damage=16,
        speed="Fast",
        abilities=[
            Ability(name="Fire Strike", description="Flaming melee attack", damage=16, effect="Burn"),
            Ability(name="Hellfire", description="Burst of demonic flames", damage=12, effect="AoE"),
        ],
        weaknesses=["Ice", "Holy"],
        resistances=["Fire"],
        experience=60,
        loot=[
            LootDrop(item="Demon Horn", chance="Common"),
            LootDrop(item="Hellfire Essence", chance="Rare"),
        ],
        icon="Δ",
        threat_level=4,
    ),
    Creature(
        id="assassin",
        name="Assassin",
        category="elite",
        description="Deadly killers who strike from the shadows. They vanish and reappear to deliver lethal backstabs.",
        appearance="Lithe figure in dark leather, face hidden behind a mask. Dual-wields curved daggers.",
        behavior="Uses stealth to approach unseen. Strikes from behind for massive damage.",
        floors="2-8",
        health=20,
        damage=14,
        speed="Very Fast",
        abilities=[
            Ability(name="Backstab", description="Devastating attack from stealth", damage=14, effect="Critical if from behind"),
            Ability(name="Vanish", description="Becomes invisible briefly", effect="Stealth"),
        ],
        weaknesses=["AoE attacks"],
        resistances=[],
        experience=35,
        loot=[
            LootDrop(item="Assassin's Blade", chance="Common"),
            LootDrop(item="Smoke Bomb", chance="Rare"),
        ],
        icon="a",
        threat_level=3,
    ),
    Creature(
        id="fire_elemental",
        name="Fire Elemental",
        category="elite",
        description="Living flames given form. They burn everything they touch and are immune to fire damage.",
        appearance="Humanoid shape composed entirely of roaring flames. Leaves scorch marks wherever it moves.",
        behavior="Uses elemental tactics, maintaining optimal range for fire attacks.",
        floors="3-8",
        health=30,
        damage=12,
        speed="Normal",
        abilities=[
            Ability(name="Fire Bolt", description="Ranged fire projectile", damage=12, effect="Burn"),
            Ability(name="Immolate", description="Sets nearby area ablaze", effect="AoE Burn"),
        ],
        weaknesses=["Ice"],
        resistances=["Fire (Immune)"],
        experience=45,
        loot=[
            LootDrop(item="Fire Core", chance="Common"),
            LootDrop(item="Ember Crystal", chance="Rare"),
        ],
        icon="F",
        threat_level=3,
    ),
    Creature(
        id="ice_elemental",
        name="Ice Elemental",
        category="elite",
        description="Frozen spirits that bring bitter cold. Their touch freezes and they shatter when destroyed.",
        appearance="Crystalline humanoid form of blue ice. Frost radiates outward in visible waves.",
        behavior="Uses elemental tactics. Slows enemies with freezing attacks.",
        floors="3-8",
        health=30,
        damage=10,
        speed="Normal",
        abilities=[
            Ability(name="Ice Shard", description="Launches frozen projectile", damage=10, effect="Slow"),
            Ability(name="Frost Nova", description="Freezes nearby enemies", effect="AoE Freeze"),
        ],
        weaknesses=["Fire"],
        resistances=["Ice (Immune)"],
        experience=45,
        loot=[
            LootDrop(item="Ice Core", chance="Common"),
            LootDrop(item="Frost Crystal", chance="Rare"),
        ],
        icon="I",
        threat_level=3,
    ),
    Creature(
        id="lightning_elemental",
        name="Lightning Elemental",
        category="elite",
        description="Crackling beings of pure electricity. Their attacks chain between targets.",
        appearance="Flickering humanoid of blue-white lightning. Constantly discharging sparks.",
        behavior="Uses elemental tactics. Attacks can jump to nearby enemies.",
        floors="4-8",
        health=25,
        damage=14,
        speed="Very Fast",
        abilities=[
            Ability(name="Chain Lightning", description="Electrical attack that jumps to nearby targets", damage=14, effect="Chain 3 targets"),
            Ability(name="Static Field", description="Damages all nearby enemies", effect="AoE"),
        ],
        weaknesses=["Dark"],
        resistances=["Lightning (Immune)"],
        experience=50,
        loot=[
            LootDrop(item="Lightning Core", chance="Common"),
            LootDrop(item="Spark Crystal", chance="Rare"),
        ],
        icon="Z",
        threat_level=3,
    ),

    # === THEMATIC ENEMIES (v5.5 floor-specific) ===
    Creature(
        id="rat",
        name="Rat",
        category="thematic",
        description="Common vermin infesting the sewers. Individually weak but dangerous in swarms.",
        appearance="Large gray rat with beady red eyes and matted fur.",
        behavior="Aggressively attacks in groups. Swarms overwhelm prey.",
        floors="2-3",
        health=5,
        damage=1,
        speed="Fast",
        abilities=[
            Ability(name="Gnaw", description="Quick biting attack", damage=1),
        ],
        weaknesses=["AoE attacks"],
        resistances=[],
        experience=8,
        loot=[
            LootDrop(item="Rat Tail", chance="Common"),
        ],
        icon="r",
        threat_level=1,
    ),
    Creature(
        id="plague_rat",
        name="Plague Rat",
        category="thematic",
        description="Disease-carrying rats from the deepest sewers. Their bites can cause lasting infection.",
        appearance="Bloated rat with patchy fur and oozing sores. Green foam at its mouth.",
        behavior="Aggressively pursues prey. Spreads disease on contact.",
        floors="2-4",
        health=7,
        damage=2,
        speed="Fast",
        abilities=[
            Ability(name="Diseased Bite", description="Infectious attack", damage=2, effect="Poison"),
        ],
        weaknesses=["Fire"],
        resistances=["Poison"],
        experience=12,
        loot=[
            LootDrop(item="Plague Tooth", chance="Common"),
            LootDrop(item="Disease Sample", chance="Rare"),
        ],
        icon="p",
        threat_level=1,
    ),
    Creature(
        id="spiderling",
        name="Spiderling",
        category="thematic",
        description="Small spiders that scout the Forest Depths for the Spider Queen. Fast and venomous.",
        appearance="Cat-sized spider with dark green carapace and eight gleaming eyes.",
        behavior="Aggressive scout. Reports intruders to larger spiders.",
        floors="3-4",
        health=6,
        damage=2,
        speed="Fast",
        abilities=[
            Ability(name="Venomous Bite", description="Quick poison attack", damage=2, effect="Poison"),
        ],
        weaknesses=["Fire"],
        resistances=[],
        experience=12,
        loot=[
            LootDrop(item="Spider Fang", chance="Common"),
        ],
        icon="x",
        threat_level=1,
    ),
    Creature(
        id="webweaver",
        name="Webweaver",
        category="thematic",
        description="Intelligent spiders that create elaborate web traps throughout the Forest Depths.",
        appearance="Large spider with intricate patterns on its back. Spinnerets glow faintly.",
        behavior="Sets web traps and waits. Attacks immobilized prey.",
        floors="3-5",
        health=9,
        damage=3,
        speed="Normal",
        abilities=[
            Ability(name="Web Trap", description="Immobilizes target in sticky web", effect="Root"),
            Ability(name="Venomous Strike", description="Poison attack", damage=3, effect="Poison"),
        ],
        weaknesses=["Fire"],
        resistances=[],
        experience=18,
        loot=[
            LootDrop(item="Spider Silk", chance="Common"),
            LootDrop(item="Webweaver Gland", chance="Rare"),
        ],
        icon="w",
        threat_level=2,
    ),
    Creature(
        id="oathbound_guard",
        name="Oathbound Guard",
        category="thematic",
        description="Spectral soldiers still guarding Mirror Valdris. Their oaths bind them beyond death.",
        appearance="Ghostly knight in ornate armor. Carries a spectral halberd. Eyes burn with cold fire.",
        behavior="Patrols and challenges intruders. Fights with disciplined tactics.",
        floors="4-6",
        health=16,
        damage=5,
        speed="Normal",
        abilities=[
            Ability(name="Halberd Strike", description="Long-reach weapon attack", damage=5),
            Ability(name="Oath's Resolve", description="Reduces damage taken temporarily", effect="Damage reduction"),
        ],
        weaknesses=["Holy"],
        resistances=["Poison", "Dark"],
        experience=35,
        loot=[
            LootDrop(item="Guard's Sigil", chance="Common"),
            LootDrop(item="Spectral Steel", chance="Rare"),
        ],
        icon="G",
        threat_level=2,
    ),
    Creature(
        id="court_scribe",
        name="Court Scribe",
        category="thematic",
        description="Ghostly bureaucrats of the fallen court. They attack with spectral quills and dark ink.",
        appearance="Translucent figure in scholar's robes. Carries floating quill and tome.",
        behavior="Maintains distance. Uses ranged attacks and summons ink constructs.",
        floors="4-6",
        health=10,
        damage=4,
        speed="Normal",
        abilities=[
            Ability(name="Ink Bolt", description="Ranged spectral attack", damage=4),
            Ability(name="Binding Contract", description="Slows target with magical bureaucracy", effect="Slow"),
        ],
        weaknesses=["Fire"],
        resistances=[],
        experience=28,
        loot=[
            LootDrop(item="Spectral Ink", chance="Common"),
            LootDrop(item="Cursed Quill", chance="Rare"),
        ],
        icon="q",
        threat_level=2,
    ),
    Creature(
        id="animated_tome",
        name="Animated Tome",
        category="thematic",
        description="Books that have absorbed too much magical knowledge and gained malevolent sentience.",
        appearance="Large leather-bound book floating in the air. Pages flutter menacingly. Teeth line the spine.",
        behavior="Aggressive. Attacks by biting and launching paper projectiles.",
        floors="6-7",
        health=14,
        damage=5,
        speed="Normal",
        abilities=[
            Ability(name="Paper Cut", description="Launches razor-sharp pages", damage=5),
            Ability(name="Knowledge Drain", description="Steals magical energy", effect="Mana drain"),
        ],
        weaknesses=["Fire"],
        resistances=["Poison", "Dark"],
        experience=40,
        loot=[
            LootDrop(item="Enchanted Page", chance="Common"),
            LootDrop(item="Tome Binding", chance="Rare"),
        ],
        icon="t",
        threat_level=2,
    ),
    Creature(
        id="crystal_sentinel",
        name="Crystal Sentinel",
        category="thematic",
        description="Guardians formed from the living crystals of the final cave. Nearly indestructible.",
        appearance="Humanoid figure of faceted crystal. Glows with inner light. Moves with grinding precision.",
        behavior="Patrols crystal formations. Attacks intruders with overwhelming force.",
        floors="8 only",
        health=22,
        damage=8,
        speed="Slow",
        abilities=[
            Ability(name="Crystal Slam", description="Heavy crushing attack", damage=8),
            Ability(name="Prismatic Beam", description="Focused light attack", damage=6, effect="Blind"),
        ],
        weaknesses=["Sonic"],
        resistances=["Ice", "Fire", "Lightning"],
        experience=70,
        loot=[
            LootDrop(item="Crystal Shard", chance="Common"),
            LootDrop(item="Sentinel Core", chance="Rare"),
        ],
        icon="C",
        threat_level=3,
    ),

    # === RARE ENEMIES (v6.5 spice enemies - one per floor) ===
    Creature(
        id="shade",
        name="Shade",
        category="rare",
        description="Ghostly remnants of prisoners who died in the Stone Dungeon. Partially incorporeal.",
        appearance="Wispy humanoid shadow with hollow eyes. Chains still dangle from translucent wrists.",
        behavior="Uses stealth to ambush. Phases through walls to attack.",
        floors="1 only",
        health=5,
        damage=3,
        speed="Fast",
        abilities=[
            Ability(name="Shadow Strike", description="Attack from stealth", damage=3),
            Ability(name="Phase", description="Passes through solid objects", effect="Intangible"),
        ],
        weaknesses=["Light", "Holy"],
        resistances=["Physical"],
        experience=20,
        loot=[
            LootDrop(item="Shadow Essence", chance="Common"),
            LootDrop(item="Prisoner's Chain", chance="Rare"),
        ],
        icon="S",
        threat_level=2,
    ),
    Creature(
        id="bile_lurker",
        name="Bile Lurker",
        category="rare",
        description="Toxic slime creature that dwells in the deepest sewer tunnels. Completely immune to poison.",
        appearance="Amorphous blob of greenish-yellow ooze. Bubbles constantly release noxious fumes.",
        behavior="Aggressively pursues prey. Leaves toxic trail.",
        floors="2 only",
        health=12,
        damage=2,
        speed="Slow",
        abilities=[
            Ability(name="Acid Touch", description="Corrosive melee attack", damage=2, effect="Armor damage"),
            Ability(name="Poison Spit", description="Ranged toxic attack", damage=3, effect="Poison"),
        ],
        weaknesses=["Fire"],
        resistances=["Poison (Immune)"],
        experience=22,
        loot=[
            LootDrop(item="Bile Sample", chance="Common"),
            LootDrop(item="Toxic Core", chance="Rare"),
        ],
        icon="B",
        threat_level=2,
    ),
    Creature(
        id="thornling",
        name="Thornling",
        category="rare",
        description="Animated thorny plant that prowls the Forest Depths. Damages attackers with its spines.",
        appearance="Walking mass of twisted vines and thorns. Rose-like flowers bloom with razor petals.",
        behavior="Chases prey. Retaliates against melee attackers automatically.",
        floors="3 only",
        health=8,
        damage=4,
        speed="Normal",
        abilities=[
            Ability(name="Thorn Strike", description="Piercing vine attack", damage=4),
            Ability(name="Thorn Burst", description="Damages melee attackers", effect="Reflect damage"),
        ],
        weaknesses=["Fire"],
        resistances=[],
        experience=25,
        loot=[
            LootDrop(item="Thorny Vine", chance="Common"),
            LootDrop(item="Rose Heart", chance="Rare"),
        ],
        icon="h",
        threat_level=2,
    ),
    Creature(
        id="doppelganger",
        name="Doppelganger",
        category="rare",
        description="Shapeshifting creature that haunts Mirror Valdris. Can mimic the appearance of others.",
        appearance="In true form: featureless gray humanoid. Can perfectly copy any creature it has seen.",
        behavior="Stalks targets, then attacks when least expected.",
        floors="4 only",
        health=15,
        damage=5,
        speed="Normal",
        abilities=[
            Ability(name="Mimic Strike", description="Copies target's attack", damage=5),
            Ability(name="Perfect Copy", description="Assumes target's appearance", effect="Disguise"),
        ],
        weaknesses=["True Sight"],
        resistances=["Dark"],
        experience=40,
        loot=[
            LootDrop(item="Shapeshifter Essence", chance="Common"),
            LootDrop(item="Mirror Shard", chance="Rare"),
        ],
        icon="?",
        threat_level=3,
    ),
    Creature(
        id="frost_wisp",
        name="Frost Wisp",
        category="rare",
        description="Frozen spirit trapped in the Ice Cavern. Beautiful but deadly cold.",
        appearance="Small glowing orb of pale blue light surrounded by swirling snowflakes.",
        behavior="Maintains distance. Fires ice shards at intruders.",
        floors="5 only",
        health=6,
        damage=6,
        speed="Fast",
        abilities=[
            Ability(name="Ice Shard", description="Ranged freezing attack", damage=6, effect="Slow"),
            Ability(name="Frost Aura", description="Chills nearby enemies", effect="AoE Slow"),
        ],
        weaknesses=["Fire"],
        resistances=["Ice (Immune)"],
        experience=35,
        loot=[
            LootDrop(item="Frost Essence", chance="Common"),
            LootDrop(item="Frozen Tear", chance="Rare"),
        ],
        icon="f",
        threat_level=2,
    ),
    Creature(
        id="ink_phantom",
        name="Ink Phantom",
        category="rare",
        description="Living manuscript that escaped its pages in the Ancient Library. Made of animate ink.",
        appearance="Humanoid shape of flowing black ink. Words and symbols constantly form and dissolve on its surface.",
        behavior="Uses stealth. Attacks from shadows with ink tendrils.",
        floors="6 only",
        health=10,
        damage=7,
        speed="Normal",
        abilities=[
            Ability(name="Ink Lash", description="Tendril attack", damage=7),
            Ability(name="Vanish", description="Dissolves into shadows", effect="Stealth"),
        ],
        weaknesses=["Fire", "Water"],
        resistances=["Dark"],
        experience=45,
        loot=[
            LootDrop(item="Living Ink", chance="Common"),
            LootDrop(item="Phantom Manuscript", chance="Rare"),
        ],
        icon="i",
        threat_level=3,
    ),
    Creature(
        id="ember_sprite",
        name="Ember Sprite",
        category="rare",
        description="Mischievous fire spirit native to the Volcanic Depths. Playful but dangerous.",
        appearance="Tiny humanoid of dancing flames. Leaves trails of embers and giggles constantly.",
        behavior="Maintains distance. Throws fire bolts while darting about.",
        floors="7 only",
        health=8,
        damage=8,
        speed="Very Fast",
        abilities=[
            Ability(name="Fire Bolt", description="Ranged fire attack", damage=8, effect="Burn"),
            Ability(name="Flame Dash", description="Quick evasive movement", effect="Dodge"),
        ],
        weaknesses=["Ice"],
        resistances=["Fire (Immune)"],
        experience=50,
        loot=[
            LootDrop(item="Ember Essence", chance="Common"),
            LootDrop(item="Sprite Flame", chance="Rare"),
        ],
        icon="e",
        threat_level=3,
    ),
    Creature(
        id="prism_watcher",
        name="Prism Watcher",
        category="rare",
        description="Crystalline eye creature that guards the Crystal Cave. Sees all and strikes with lightning.",
        appearance="Floating crystal orb with a single massive eye. Smaller eyes orbit around it. Crackles with electricity.",
        behavior="Hovers at range. Uses elemental tactics with chain lightning.",
        floors="8 only",
        health=18,
        damage=9,
        speed="Normal",
        abilities=[
            Ability(name="Chain Lightning", description="Electrical attack that chains between targets", damage=9, effect="Chain"),
            Ability(name="All-Seeing Eye", description="Cannot be surprised or ambushed", effect="True Sight"),
        ],
        weaknesses=["Dark"],
        resistances=["Lightning"],
        experience=65,
        loot=[
            LootDrop(item="Prism Lens", chance="Common"),
            LootDrop(item="Eye of the Watcher", chance="Rare"),
        ],
        icon="P",
        threat_level=4,
    ),

    # === BOSSES (one per floor) ===
    Creature(
        id="goblin_king",
        name="Goblin King",
        title="Warden of the Stone Dungeon",
        category="boss",
        description="A crowned goblin wielding a bloodied mace. He rules over the goblin hordes of Floor 1 with brutal authority.",
        appearance="Larger goblin wearing a crude iron crown. Carries a bloodstained mace and wears trophy bones.",
        behavior="Commands goblin minions. Uses war cry to rally troops.",
        floors="1 (Boss)",
        health=50,
        damage=5,
        speed="Normal",
        abilities=[
            Ability(name="Mace Smash", description="Heavy weapon attack", damage=5),
            Ability(name="Summon Goblins", description="Calls goblin reinforcements", effect="Summon 2-3 goblins"),
            Ability(name="War Cry", description="Empowers nearby goblins", effect="Allies +50% damage"),
        ],
        weaknesses=[],
        resistances=[],
        experience=200,
        loot=[
            LootDrop(item="Iron Sword", chance="Guaranteed"),
            LootDrop(item="Chain Mail", chance="Guaranteed"),
        ],
        icon="K",
        threat_level=3,
    ),
    Creature(
        id="rat_king",
        name="Rat King",
        title="Lord of the Sewers",
        category="boss",
        description="A grotesque fusion of rats bound by diseased flesh. The undisputed ruler of the Sewers of Valdris.",
        appearance="Mass of intertwined rats sharing a single body. Multiple heads snap and screech. Oozes plague.",
        behavior="Summons rat swarms. Uses burrow to ambush. Spreads disease.",
        floors="2 (Boss)",
        health=65,
        damage=9,
        speed="Normal",
        abilities=[
            Ability(name="Gnashing Teeth", description="Multi-bite attack", damage=9),
            Ability(name="Summon Swarm", description="Calls waves of rats", effect="Summon rat swarm"),
            Ability(name="Plague Bite", description="Infectious attack", damage=6, effect="Poison + Disease"),
            Ability(name="Burrow", description="Digs underground to reposition", effect="Untargetable briefly"),
        ],
        weaknesses=["Fire"],
        resistances=["Poison"],
        experience=200,
        loot=[
            LootDrop(item="Plague Blade", chance="Guaranteed"),
            LootDrop(item="Rat King Crown", chance="Guaranteed"),
        ],
        icon="r",
        threat_level=3,
    ),
    Creature(
        id="spider_queen",
        name="Spider Queen",
        title="Matriarch of the Forest Depths",
        category="boss",
        description="A massive arachnid matriarch dripping with venom. Mother to all spiders in the Forest Depths.",
        appearance="Elephant-sized spider with iridescent carapace. Egg sac pulses on her abdomen. Eight eyes gleam with malice.",
        behavior="Creates web traps. Summons spiderlings. Uses powerful venom.",
        floors="3 (Boss)",
        health=70,
        damage=10,
        speed="Normal",
        abilities=[
            Ability(name="Venomous Fang", description="Devastating poison bite", damage=10, effect="Heavy Poison"),
            Ability(name="Web Trap", description="Immobilizes target in web", effect="Root + Damage over time"),
            Ability(name="Poison Bite", description="Secondary venom attack", damage=6, effect="Poison"),
            Ability(name="Summon Spiders", description="Calls spiderling swarm", effect="Summon 3-5 spiderlings"),
        ],
        weaknesses=["Fire"],
        resistances=["Poison"],
        experience=400,
        loot=[
            LootDrop(item="Spider Silk Armor", chance="Guaranteed"),
            LootDrop(item="Venom Dagger", chance="Guaranteed"),
        ],
        icon="S",
        threat_level=4,
    ),
    Creature(
        id="the_regent",
        name="The Regent",
        title="The Monarch Who Never Was",
        category="boss",
        description="A monarch who never was, wearing a crown of stolen memories. Rules Mirror Valdris with illusory authority.",
        appearance="Regal figure in ornate robes. Face constantly shifts between different rulers. Crown glows with stolen power.",
        behavior="Commands oathbound guards. Uses illusions and mind control.",
        floors="4 (Boss)",
        health=95,
        damage=13,
        speed="Normal",
        abilities=[
            Ability(name="Royal Strike", description="Scepter attack", damage=13),
            Ability(name="Royal Decree", description="Compels target to bow", effect="Stun"),
            Ability(name="Summon Guard", description="Calls oathbound protector", effect="Summon elite guard"),
            Ability(name="Counterfeit Crown", description="Steals target's abilities temporarily", effect="Copy one ability"),
        ],
        weaknesses=["True Sight", "Holy"],
        resistances=["Dark", "Psychic"],
        experience=550,
        loot=[
            LootDrop(item="Royal Scepter", chance="Guaranteed"),
            LootDrop(item="Counterfeit Crown", chance="Guaranteed"),
        ],
        icon="R",
        threat_level=4,
    ),
    Creature(
        id="frost_giant",
        name="Frost Giant",
        title="The Frozen Titan",
        category="boss",
        description="A towering giant encased in eternal ice. Guardian of the Ice Cavern's deepest reaches.",
        appearance="Twenty-foot humanoid of ice and frozen flesh. Beard of icicles. Eyes like frozen lakes.",
        behavior="Slow but devastating. Uses area frost attacks.",
        floors="5 (Boss)",
        health=80,
        damage=12,
        speed="Slow",
        abilities=[
            Ability(name="Frozen Fist", description="Crushing ice attack", damage=12),
            Ability(name="Ice Blast", description="Cone of freezing wind", damage=8, effect="AoE Freeze"),
            Ability(name="Freeze Ground", description="Creates ice hazard area", effect="Slippery terrain + damage"),
        ],
        weaknesses=["Fire"],
        resistances=["Ice (Immune)", "Physical"],
        experience=300,
        loot=[
            LootDrop(item="Frost Axe", chance="Guaranteed"),
            LootDrop(item="Ice Shield", chance="Guaranteed"),
        ],
        icon="F",
        threat_level=4,
    ),
    Creature(
        id="arcane_keeper",
        name="Arcane Keeper",
        title="Guardian of Forbidden Knowledge",
        category="boss",
        description="A spectral guardian of forbidden knowledge. Protects the Ancient Library from those unworthy.",
        appearance="Floating specter in scholar's robes. Multiple phantom arms hold ancient tomes. Eyes glow with arcane light.",
        behavior="Teleports around battlefield. Uses devastating magic attacks.",
        floors="6 (Boss)",
        health=80,
        damage=14,
        speed="Fast",
        abilities=[
            Ability(name="Arcane Bolt", description="Powerful magic projectile", damage=14),
            Ability(name="Teleport", description="Instantly relocates", effect="Blink to new position"),
            Ability(name="Knowledge Drain", description="Steals magical power", effect="Mana drain + self heal"),
        ],
        weaknesses=["Physical attacks", "Fire"],
        resistances=["Magic"],
        experience=800,
        loot=[
            LootDrop(item="Teleport Scroll", chance="Guaranteed"),
            LootDrop(item="Teleport Scroll", chance="Guaranteed"),
            LootDrop(item="Strength Potion", chance="Guaranteed"),
        ],
        icon="A",
        threat_level=4,
    ),
    Creature(
        id="flame_lord",
        name="Flame Lord",
        title="Master of the Volcanic Forge",
        category="boss",
        description="A being of pure fire born from the volcanic depths. Commands all flame in the Volcanic Depths.",
        appearance="Towering humanoid of magma and flame. Crown of fire. Molten rock flows where blood should be.",
        behavior="Extremely aggressive. Creates lava hazards. Devastating fire attacks.",
        floors="7 (Boss)",
        health=100,
        damage=15,
        speed="Normal",
        abilities=[
            Ability(name="Magma Strike", description="Molten melee attack", damage=15, effect="Burn"),
            Ability(name="Fire Breath", description="Cone of flames", damage=12, effect="AoE Burn"),
            Ability(name="Lava Pool", description="Creates damaging terrain", effect="Lava hazard"),
            Ability(name="Inferno", description="Massive fire explosion", damage=20, effect="Room-wide AoE"),
        ],
        weaknesses=["Ice"],
        resistances=["Fire (Immune)"],
        experience=500,
        loot=[
            LootDrop(item="Flame Sword", chance="Guaranteed"),
            LootDrop(item="Fire Resist Ring", chance="Guaranteed"),
        ],
        icon="Φ",
        threat_level=5,
    ),
    Creature(
        id="dragon_emperor",
        name="Dragon Emperor",
        title="Lord of the Crystal Hoard",
        category="boss",
        description="The ancient dragon lord guarding the ultimate treasure. Final boss of the Crystal Cave.",
        appearance="Massive dragon with crystalline scales. Wings span the entire chamber. Eyes hold ancient intelligence.",
        behavior="Uses all dragon abilities. Inspires fear. Devastatingly powerful.",
        floors="8 (Final Boss)",
        health=200,
        damage=20,
        speed="Normal",
        abilities=[
            Ability(name="Dragon Claw", description="Devastating melee attack", damage=20),
            Ability(name="Fire Breath", description="Massive cone of flames", damage=25, effect="AoE Burn"),
            Ability(name="Tail Sweep", description="Knockback attack", damage=15, effect="Knockback"),
            Ability(name="Dragon Fear", description="Terrifying roar", effect="Fear + Stun"),
        ],
        weaknesses=["Ice", "Lightning"],
        resistances=["Fire"],
        experience=1500,
        loot=[
            LootDrop(item="Dragon Slayer", chance="Guaranteed"),
            LootDrop(item="Dragon Scale", chance="Guaranteed"),
        ],
        icon="E",
        threat_level=5,
    ),
]
